version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: deps
          command: make deps
      - run:
          name: lint
          command: make lint
      - run:
          name: test
          command: make test
      - run:
          name: docker_build
          command: make docker_build
      - run:
          name: docker_login
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: docker_push
          command: make docker_push

workflows:
  build-and-test:
    jobs:
      - build-and-test

